### PR TITLE
#68: Add service restart retries

### LINKED ISSUE #68: broker restart fails
The `/var/log/kafka/kafka_init_stdout.log` file showed:

```
No kafka server to stop
```

for this chef-client failure:

```
  * service[kafka] action stop

    ================================================================================
    Error executing action `stop` on resource 'service[kafka]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of /sbin/service kafka stop ----
    STDOUT: Attempting to shutdown Kafka...
    Attempting to shutdown Kafka...
    Error stopping Kafka
    STDERR:
    ---- End output of /sbin/service kafka stop ----
    Ran /sbin/service kafka stop returned 1

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/cerner_kafka/recipes/default.rb

    207: service "kafka" do
    208:   action [:enable, :start]
    209:   supports :status => true, :restart => true
    210: end
    211:

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/cerner_kafka/recipes/default.rb:207:in `from_file'

    service("kafka") do
      action [:enable, :start]
      supports {:status=>true, :restart=>true}
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      service_name "kafka"
      enabled nil
      running nil
      masked nil
      pattern "kafka"
      declared_type :service
      cookbook_name "cerner_kafka"
      recipe_name "default"
    end
```

when attempting to update from 2.2.0 to 2.2.1

I don't know what exactly changed to cause this to start happening, but the cookbook should be more robust and not fail out if it can't stop a broker because it was not detected as running.

### PR DESCRIPTION
**Pull request by noslowerdna**
Fixes #68

### CODE REVIEW

File: recipes/default.rb [hunk 1]
```diff
@@ -207,6 +207,8 @@
 service "kafka" do
   action [:enable, :start]
   supports :status => true, :restart => true
+  retries 2
+  retry_delay 5
```
Comment (bbaugher) [inline recipes/default.rb]: Do you think its worth making this configurable?

Comment (noslowerdna) [reply recipes/default.rb]: I didn't think so - if these were Chef's defaults (rather than the actual 0 retries, 2 seconds apart) I think we would be fine with that. There are some configurable sleep times in the init.d script which should cover most transient issues already.

**Review by bbaugher — APPROVED** [review]

**Review by gwhitsitt — APPROVED** [review]
